### ISSUE TITLE
I just wanted to say Thank you!  

### ISSUE THREAD

**Issue by SafariKC** [Kwintenvdb/homebridge-divoom#1]
I just wanted to say Thanks!

I have the Tivoo-Max-light and it seems to work great so far!  Nice to have this in HomeKit!

**Comment by Kwintenvdb** [comment]
Very welcome! Major credits go to https://github.com/RomRider/node-divoom-timebox-evo for doing most of the legwork here and exposing the API of the Divoom devices so beautifully, I've also added attribution to them in the README.
